# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |               Task: 1.3       - Repos per OS                       |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

# For each supported 'distribution_id' we want a list of dictionary entries that
# specify the associated tier (or 'all' to always match), the repository name name
# See the definition of 'distribution_full_id' to determine what to use when
# creating an entry for a new distribution.
# For example, XX.Y where XX is the major version and Y is the minor version
repos:
  redhat7.4:
    - { tier:   'os', repo: 'epel', url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm', state: 'absent' }
  redhat7.6:
    - { tier:   'os', repo: 'epel', url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm', state: 'absent' }
  redhat7.7:
    - { tier:   'os', repo: 'epel', url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm', state: 'absent' }
  redhat7.9:
    - { tier:   'os', repo: 'epel', url: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm', state: 'absent' }
  redhat8.1:
  redhat8.2:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm', state: 'present' }
  redhat8.4:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm', state: 'present' }
  redhat8.6:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm', state: 'present' }
  redhat8.8:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm', state: 'present' }
  redhat8.9:
  redhat8.10:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm', state: 'present' }
  redhat9.0:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/9/packages-microsoft-prod.rpm', state: 'present' }
  redhat9.2:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/9/packages-microsoft-prod.rpm', state: 'present' }
  redhat9.4:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/9/packages-microsoft-prod.rpm', state: 'present' }
  redhat9.6:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/9/packages-microsoft-prod.rpm', state: 'present' }
  redhat10.0:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/10/packages-microsoft-prod.rpm', state: 'present' }

  # SLES
  sles12.3:
  sles_sap12.3:
  sles_sap12.4:
  sles_sap12.5:
  sles_sap15.1:
  sles_sap15.2:
  sles_sap15.3:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/sles/15/packages-microsoft-prod.rpm', state: 'present' }
  sles_sap15.4:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/sles/15/packages-microsoft-prod.rpm', state: 'present' }
  sles_sap15.5:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/sles/15/packages-microsoft-prod.rpm', state: 'present' }
  sles_sap15.6:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/sles/15/packages-microsoft-prod.rpm', state: 'present' }
  sles_sap15.7:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/sles/15/packages-microsoft-prod.rpm', state: 'present' }
  sles15.3:
  sles15.4:
  sles15.5:
  sles15.6:

  # Oracle
  # Adding the entries for Oracle-Linux for testing. cat /etc/oracle-release is the command to get the os version info in Oracle linux.
  oraclelinux8.1:
  oraclelinux8.2:
  oraclelinux8.3:
  oraclelinux8.4:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm', state: 'present' }
  oraclelinux8.5:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm', state: 'present' }
  oraclelinux8.6:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm', state: 'present' }
  oraclelinux8.7:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm', state: 'present' }
  oraclelinux8.8:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm', state: 'present' }
  oraclelinux8.9:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm', state: 'present' }
  oraclelinux8.10:
    - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm', state: 'present' }
  oraclelinux9.0:
      - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/9/packages-microsoft-prod.rpm', state: 'present' }
  oraclelinux9.2:
      - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/9/packages-microsoft-prod.rpm', state: 'present' }
  oraclelinux9.4:
      - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/9/packages-microsoft-prod.rpm', state: 'present' }
  oraclelinux9.6:
      - { tier:   'os', repo: 'microsoft', url: 'https://packages.microsoft.com/config/rhel/9/packages-microsoft-prod.rpm', state: 'present' }
