# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |               This pipeline deploys the Workload Zone                      |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

parameters:

  - name:                              workload_zone_name
    displayName:                       "Workload zone configuration name, use the following syntax: ENV-LOCA-VNET"
    type:                              string
    default:                           DEV-WEEU-SAP01

  - name:                              control_plane_name
    displayName:                       "Control plane name, use the following syntax: ENV-LOCA-VNET"
    type:                              string
    default:                           CPLN-NOEU-DEP01

  - name:                              inherit_settings
    displayName:                       Inherit Terraform state file information from control plane
    type:                              boolean
    default:                           true

  - name:                              sap_automation_repo_path
    displayName:                       The local path on the agent where the sap_automation repo can be found
    type:                              string

  - name:                              config_repo_path
    displayName:                       The local path on the agent where the config repo can be found
    type:                              string

  - name:                              test
    type:                              boolean
    default:                           false

stages:
  - stage: Deploy_SAP_workload_zone
    condition: and(not(failed()), not(canceled()))
    displayName: Deploy SAP workload zone
    variables:
      - template:                      variables/02-sap-workload-zone-variables.yaml
        parameters:
          workload_zone_name:          ${{ parameters.workload_zone_name }}
          control_plane_name:          ${{ parameters.control_plane_name }}
          inherit_settings:            ${{ parameters.inherit_settings }}
    jobs:
      - job:                           Deploy_SAP_workload_zone
        displayName:                   Deploy SAP workload zone
        workspace:
          clean:                       all
        steps:
          - template:                  templates\download.yaml
          - task:                      PostBuildCleanup@4
          - task:                      Bash@3
            name:                      ParameterValidation
            displayName:               Parameter Validation
            inputs:
              targetType:              'filePath'
              filePath:                "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/00-validate-credentials.sh"
              failOnStderr:            false
              workingDirectory:        "$(System.DefaultWorkingDirectory)"
            env:
              AZURE_DEVOPS_EXT_PAT:    $(System.AccessToken)
              SYSTEM_COLLECTIONURI:    $(System.CollectionUri)
              SYSTEM_TEAMPROJECT:      $(System.TeamProject)
          - task:                      Bash@3
            inputs:
              targetType:              'filePath'
              filePath:                "$(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/02-sap-workload-zone.sh"
              failOnStderr:            false
              workingDirectory:        "$(System.DefaultWorkingDirectory)"
            displayName:               Deploy SAP Workload Zone
            env:
              APPLICATION_CONFIGURATION_ID: $(APPLICATION_CONFIGURATION_ID)
              ARM_CLIENT_ID:                $(ParameterValidation.ARM_CLIENT_ID)
              ARM_CLIENT_SECRET:            $(ParameterValidation.ARM_CLIENT_SECRET)
              ARM_OBJECT_ID:                $(ParameterValidation.ARM_OBJECT_ID)
              ARM_SUBSCRIPTION_ID:          $(ParameterValidation.ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID:                $(ParameterValidation.ARM_TENANT_ID)
              AZURE_DEVOPS_EXT_PAT:         $(System.AccessToken)
              CONFIG_REPO_PATH:             ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
              CONTROL_PLANE_NAME:           ${{ parameters.control_plane_name }}
              LOGON_USING_SPN:              $(Logon_Using_SPN)
              SAP_AUTOMATION_REPO_PATH:     ${{ parameters.sap_automation_repo_path }}
              SYSTEM_ACCESSTOKEN:           $(System.AccessToken)
              TEST_ONLY:                    ${{ parameters.test }}
              TF_IN_AUTOMATION:             true
              TF_LOG:                       $(TF_LOG)
              USE_MSI:                      $(Use_MSI)
