# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |      This pipeline removes the Control Plane via Terraform.                |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

parameters:

  - name:                              control_plane_name
    displayName:                       "Control Plane configuration name, use this format: ENV-LOCA-VNET"
    type:                              string
    default:                           MGMT-WEEU-DEP01

  - name:                              use_deployer
    displayName:                       Run removal on self hosted agent
    type:                              boolean
    default:                           false

  - name:                              sap_automation_repo_path
    displayName:                       The local path on the agent where the sap_automation repo can be found
    type:                              string

  - name:                              config_repo_path
    displayName:                       The local path on the agent where the config repo can be found
    type:                              string

  - name:                              connection_name
    displayName:                       Service Connection Name
    type:                              string

stages:
  - stage:                             Remove_control_plane_remote
    displayName:                       "Control plane removal (on self hosted agent)"
    variables:
      - template:                      variables/12-remove-control-plane-variables.yaml
        parameters:
          control_plane_name:          ${{ parameters.control_plane_name }}
          use_deployer:                ${{ parameters.use_deployer }}
    pool:
      name:                            $(POOL)
    jobs:
      - job:                           Remove_control_plane_remote
        displayName:                   "Start control plane removal"
        variables:
          - group:                     SDAF-${{ parameters.control_plane_name }}
        workspace:
          clean:                       all
        steps:
          - template:                  templates\download.yaml
          - task:                      PostBuildCleanup@4
          - task:                      AzureCLI@2
            continueOnError:           false
            inputs:
              azureSubscription:       "${{ parameters.control_plane_name }}_Service_Connection"
              scriptType:              bash
              scriptLocation:          'scriptPath'
              scriptPath:              $(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/12-remove-control-plane.sh
              addSpnToEnvironment:     true
              visibleAzLogin:          false
              failOnStandardError:     false
            displayName:               Remove control plane
            env:
              APPLICATION_CONFIGURATION_NAME:        $(APPLICATION_CONFIGURATION_NAME)
              APP_REGISTRATION_APP_ID:               $(APP_REGISTRATION_APP_ID)
              ARM_SUBSCRIPTION_ID:                   $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID:                         $(ParameterValidation.ARM_TENANT_ID)
              ARM_USE_MSI:                           true
              AZURE_DEVOPS_EXT_PAT:                  $(System.AccessToken)
              CLIENT_ID:                             $(ARM_CLIENT_ID)
              CONFIG_REPO_PATH:                      ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
              OBJECT_ID:                             $(ARM_OBJECT_ID)
              SAP_AUTOMATION_REPO_PATH:              ${{ parameters.sap_automation_repo_path }}
              SYSTEM_ACCESSTOKEN:                    $(System.AccessToken)
              TERRAFORM_REMOTE_STORAGE_ACCOUNT_NAME: $(TERRAFORM_REMOTE_STORAGE_ACCOUNT_NAME)
              TF_IN_AUTOMATION:                      true
              TF_LOG:                                $(TF_LOG)
              TF_VAR_app_registration_app_id:        $(APP_REGISTRATION_APP_ID)
              USE_MSI:                               $(Use_MSI)
  - stage:                              Remove_control_plane
    displayName:                        "Finalize control plane removal"
    variables:
      - template:                       variables/12-remove-control-plane-variables.yaml
        parameters:
          control_plane_name:           ${{ parameters.control_plane_name }}
          use_deployer:                 ${{ parameters.use_deployer }}
    pool:
      name:                             $(Agent)
    dependsOn:
      - Remove_control_plane_remote
    condition:                          in(dependencies.Remove_control_plane_remote.result, 'Succeeded', 'Skipped')
    jobs:
      - job:                            Remove_control_plane
        displayName:                    "Finalize control plane removal"
        variables:
          - group:                     SDAF-${{ parameters.control_plane_name }}
        workspace:
          clean:                       all
        steps:
          - template:                  templates\download.yaml
            parameters:
              getLatestFromBranch:     true
          - task:                      TerraformInstaller@1
            displayName:               Install terraform
            inputs:
              terraformVersion:        latest
          - task:                      PostBuildCleanup@4
          - task:                      AzureCLI@2
            continueOnError:           false
            inputs:
              azureSubscription:       "${{ parameters.control_plane_name }}_Service_Connection"
              scriptType:              bash
              scriptLocation:          'scriptPath'
              scriptPath:              $(System.DefaultWorkingDirectory)/sap-automation/deploy/scripts/pipeline_scripts/12-remove-control-plane-finalize.sh
              addSpnToEnvironment:     true
              visibleAzLogin:          false
              failOnStandardError:     false

            displayName:               Remove control plane
            env:
              ARM_USE_MSI:                     true
              AZURE_DEVOPS_EXT_PAT:            $(System.AccessToken)
              CLIENT_ID:                       $(ARM_CLIENT_ID)
              CONFIG_REPO_PATH:                ${{ parameters.config_repo_path }}/$(Deployment_Configuration_Path)
              OBJECT_ID:                       $(ARM_OBJECT_ID)
              SAP_AUTOMATION_REPO_PATH:        ${{ parameters.sap_automation_repo_path }}
              SYSTEM_ACCESSTOKEN:              $(System.AccessToken)
              TF_IN_AUTOMATION:                true
              TF_LOG:                          $(TF_LOG)
              TF_VAR_app_registration_app_id:  $(APP_REGISTRATION_APP_ID)
              USE_MSI:                         $(Use_MSI)
              key_vault:                       $(Deployer_Key_Vault)
