# /*---------------------------------------------------------------------------8
# |                                                                            |
# |     This workflows deploys the SAP Workload Zone with GitHub Actions       |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

name: Download SAP software
run-name: Download SAP software @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      bom_base_name:
        description: "Name of Bill of Materials (BoM)"
        required: true
        type: choice
        options:
          - NW750_HANA_v0004ms
      deployer:
        description: "Control Plane Environment"
        required: true
        type: environment
      region:
        description: "Control Plane Region"
        required: true
        type: string
        default: westurope
      re_download:
        description: "Re-download"
        type: boolean
        default: false

permissions:
  contents: write
  id-token: write
  issues: write

jobs:
  prepare_download:
    name: Prepare Download
    environment: ${{ inputs.deployer }}
    runs-on: self-hosted
    container:
      image: ghcr.io/devanshjainms/sap-automation:experimentalga
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get app token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          #organization: ${{ github.repository_owner }}

      - name: Azure Login
        uses: Azure/Login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Prepare SAP software download
        run: |
          cd ${SAP_AUTOMATION_REPO_PATH}
          deploy/automation/04-sap-software-download/01-prepare-software-download.sh
        env:
          APP_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          bom_base_name: ${{ inputs.bom_base_name }}
          region: ${{ inputs.region }}
          environment: ${{ inputs.deployer }}
          re_download: ${{ inputs.re_download }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          SUsername: ${{ secrets.S_USERNAME }}
          SPassword: ${{ secrets.S_PASSWORD }}
          USE_MSI: false
          deployerconfig: ${{ inputs.deployer }}.tfvars
          deployerfolder: ${{ inputs.deployer }}
